# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 951c164b01f93483e1009bd6ccbe415220f152b42f3e35d28479364b3062153d9537930e22bb96433c452a1372e19042ddfaec52d8034a794b44bd3aa9d04681

test:
  secret_key_base: c626e4d3bac74415cbade78a136f962f9449adff9e2c6d5328d18d740706a81a1123b294f54a00ed42653487d7ec8547ba2252259ce43386c1a08c52f415042c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
